name: C/C++ CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - name: compile
        run: make compile-optimized
