name: Simpl CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - name: compile
        run: make compile-optimized
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile
        working-directory: src
        run: make compile-optimized
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: tests-runner/package-lock.json
          node-version: 20.x
      - name: install dependencies
        working-directory: tests-runner
        run: npm install
      - name: build test runner
        working-directory: tests-runner
        run: npm run build
      - name: run tests
        working-directory: tests-runner
        run: node dist/index.js --vm="../src/main.run" --tests="../tests/language" --mode=integration 

